<div class="jumbotron">
    <div class="row">
        <div class="col-md-4 col-lg-offset-4">
            <?php
            $flash = $this->flashMessenger();
            echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger')); ?>
        </div>
    </div>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-xs-12 col-md-offset-3">
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <i class="fa fa-clock-o fa-fw"></i> Faça seu Login
                        </div>
                        <div class="panel-body">
                            <?php
                                $form = new \Login\Form\LoginForm();
                                $form->setAttribute('action', $this->url('login', array('action' => 'logar')));
                                $form->prepare();
                                echo $this->form()->openTag($form);
                            ?>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="emailLogin">Email: </label>
                                        <?php echo $this->formEmail($form->get('emailLogin')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="emailLogin">Senha: </label>
                                        <?php echo $this->formPassword($form->get('passwordLogin')); ?>
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    <?php echo $this->formReset($form->get('resetLogin')); ?>
                                </div>
                                <div class="col-md-6">
                                    <?php echo $this->formSubmit($form->get('submitLogin')); ?>
                                </div>
                                <?php echo $this->form()->closeTag(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>