<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SPessoa extends \Application\Entity\SPessoa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'nuSeqSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'cpfSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'nomeSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'logradouroSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'numEndSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'complementoSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'bairroSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'cepSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'telFixoSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'telCelSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'emailSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'senhaSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'stAtivoSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'dtCadastroSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'sCidadeNuSeqCidade'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'nuSeqSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'cpfSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'nomeSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'logradouroSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'numEndSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'complementoSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'bairroSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'cepSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'telFixoSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'telCelSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'emailSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'senhaSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'stAtivoSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'dtCadastroSpessoa', '' . "\0" . 'Application\\Entity\\SPessoa' . "\0" . 'sCidadeNuSeqCidade'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SPessoa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNuSeqSpessoa()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNuSeqSpessoa();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuSeqSpessoa', []);

        return parent::getNuSeqSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuSeqSpessoa($nuSeqSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuSeqSpessoa', [$nuSeqSpessoa]);

        return parent::setNuSeqSpessoa($nuSeqSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpfSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpfSpessoa', []);

        return parent::getCpfSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpfSpessoa($cpfSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpfSpessoa', [$cpfSpessoa]);

        return parent::setCpfSpessoa($cpfSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeSpessoa', []);

        return parent::getNomeSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeSpessoa($nomeSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeSpessoa', [$nomeSpessoa]);

        return parent::setNomeSpessoa($nomeSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogradouroSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogradouroSpessoa', []);

        return parent::getLogradouroSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogradouroSpessoa($logradouroSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogradouroSpessoa', [$logradouroSpessoa]);

        return parent::setLogradouroSpessoa($logradouroSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumEndSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumEndSpessoa', []);

        return parent::getNumEndSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumEndSpessoa($numEndSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumEndSpessoa', [$numEndSpessoa]);

        return parent::setNumEndSpessoa($numEndSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplementoSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplementoSpessoa', []);

        return parent::getComplementoSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplementoSpessoa($complementoSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplementoSpessoa', [$complementoSpessoa]);

        return parent::setComplementoSpessoa($complementoSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getBairroSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairroSpessoa', []);

        return parent::getBairroSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setBairroSpessoa($bairroSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairroSpessoa', [$bairroSpessoa]);

        return parent::setBairroSpessoa($bairroSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCepSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCepSpessoa', []);

        return parent::getCepSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setCepSpessoa($cepSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCepSpessoa', [$cepSpessoa]);

        return parent::setCepSpessoa($cepSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelFixoSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelFixoSpessoa', []);

        return parent::getTelFixoSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelFixoSpessoa($telFixoSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelFixoSpessoa', [$telFixoSpessoa]);

        return parent::setTelFixoSpessoa($telFixoSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelCelSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelCelSpessoa', []);

        return parent::getTelCelSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelCelSpessoa($telCelSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelCelSpessoa', [$telCelSpessoa]);

        return parent::setTelCelSpessoa($telCelSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailSpessoa', []);

        return parent::getEmailSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailSpessoa($emailSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailSpessoa', [$emailSpessoa]);

        return parent::setEmailSpessoa($emailSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenhaSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenhaSpessoa', []);

        return parent::getSenhaSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenhaSpessoa($senhaSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenhaSpessoa', [$senhaSpessoa]);

        return parent::setSenhaSpessoa($senhaSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getStAtivoSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAtivoSpessoa', []);

        return parent::getStAtivoSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAtivoSpessoa($stAtivoSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAtivoSpessoa', [$stAtivoSpessoa]);

        return parent::setStAtivoSpessoa($stAtivoSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCadastroSpessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCadastroSpessoa', []);

        return parent::getDtCadastroSpessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCadastroSpessoa($dtCadastroSpessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCadastroSpessoa', [$dtCadastroSpessoa]);

        return parent::setDtCadastroSpessoa($dtCadastroSpessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getSCidadeNuSeqCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSCidadeNuSeqCidade', []);

        return parent::getSCidadeNuSeqCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setSCidadeNuSeqCidade($sCidadeNuSeqCidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSCidadeNuSeqCidade', [$sCidadeNuSeqCidade]);

        return parent::setSCidadeNuSeqCidade($sCidadeNuSeqCidade);
    }

}
