<?= $this->doctype() ?>
<?php
$session = new \Zend\Session\Container("login");
$nomePessoa = $session->nomePessoa;

?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clinnet - Cardiologia Especializada</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="<?php echo $this->basePath('css/bootstrap.min.css');?>" >

    <!-- MetisMenu CSS -->
    <link rel="stylesheet" href="<?php echo $this->basePath('css/metisMenu.min.css');?>" >

    <!-- DataTables CSS -->
    <link rel="stylesheet" href="<?php echo $this->basePath('css/dataTables.bootstrap.css');?>" >

    <!-- DataTables Responsive CSS -->
    <link rel="stylesheet" href="<?php echo $this->basePath('css/dataTables.responsive.css');?>" >

    <!-- Custom CSS -->
    <link rel="stylesheet" href="<?php echo $this->basePath('css/sb-admin-2.css');?>" >

    <!-- Morris Charts CSS -->
    <link rel="stylesheet" href="<?php echo $this->basePath('css/morris.css');?>" >

    <!-- Custom Fonts -->
    <link rel="stylesheet" href="<?php echo $this->basePath('css/font-awesome.min.css');?>" >

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">Clinnet - Cardiologia Especializada</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">

            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-comment fa-fw"></i> New Comment
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                <span class="pull-right text-muted small">12 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-envelope fa-fw"></i> Message Sent
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-tasks fa-fw"></i> New Task
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text-center" href="#">
                            <strong>See All Alerts</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
                <!-- /.dropdown-alerts -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i>Meu Perfil</a>
                    </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Configurações</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="/login/logout"><i class="fa fa-sign-out fa-fw"></i> Sair</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="/admin"><i class="fa fa-dashboard fa-fw"></i> Início</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Administrativo<span class="fa arrow"></span></a>
                        <!-- /.nav-second-level -->
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="/funcionario">Manter Funcionários</a>
                            </li>
                            <li>
                                <a href="morris.html">Manter Pacientes</a>
                            </li>
                            <li>
                                <a href="morris.html">Manter Medicamentos</a>
                            </li>
                            <li>
                                <a href="morris.html">Manter Exames</a>
                            </li>
                            <li>
                                <a href="morris.html">Manter Mensagem</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="tables.html"><i class="fa fa-table fa-fw"></i> Manter Consultas</a>
                    </li>
                    <li>
                        <a href="tables.html"><i class="fa fa-table fa-fw"></i> Manter Receitas</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-wrench fa-fw"></i> Manter Exames<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="panels-wells.html">Solicitar Exame</a>
                            </li>
                            <li>
                                <a href="buttons.html">Cancelar Solicitação</a>
                            </li>
                            <li>
                                <a href="notifications.html">Resultados dos Exames</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Relatórios<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="flot.html">Histórico Consultas</a>
                            </li>
                            <li>
                                <a href="morris.html">Histórico Exames</a>
                            </li>
                            <li>
                                <a href="morris.html">Histórico Receitas</a>
                            </li>
                            <li>
                                <a href="morris.html">Histórico Medicamentos Prescritos</a>
                            </li>
                            <li>
                                <a href="flot.html">Histórico Internações </a>
                            </li>
                            <li>
                                <a href="flot.html">Histórico Cirurgias </a>
                            </li>

                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header">Bem Vindo Sr(a): <?php echo $nomePessoa; ?> </h5>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-lg-12">
                <?= $this->content ?>
            </div>
        </div>
    </div>
    <!-- /#page-wrapper -->
</div>
<!-- /#wrapper -->

<?php $uri = explode("/", $this->serverUrl(true));
if(isset($uri['4'])) { $pgname = $uri['4'].'.js'; } else {$pgname = "index.js"; };
?>

<!-- jQuery -->
<script src="<?php echo $this->basePath('js/jquery-2.1.1.js'); ?>"></script>

<!-- jQuery da página -->
<script src="<?php echo $this->basePath('js/'.$uri['3'].'/'.$pgname); ?>"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath('js/bootstrap.js'); ?>"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="<?php echo $this->basePath('js/metisMenu.min.js'); ?>"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath('js/jquery.dataTables.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('js/dataTables.responsive.js'); ?>"></script>


<!-- Custom Theme JavaScript -->
<script src="<?php echo $this->basePath('js/sb-admin-2.js'); ?>"></script>

</body>

</html>
